### ISSUE TITLE
No limit on fatigue

### ISSUE THREAD

**Issue by jmdejong** [modgethanc/plaintxtmines#5]
The fatigue will increase without limit on exponential growth.

I tried testing out the fatigue, and because the messages have a delay sometimes I kept striking.

Now I can't mine anymore for the next 2 years.

I feel like it's a bad thing to exclude players from the game over someting like this.

**Comment by modgethanc** [comment]
acknowledged; making a note here for myself to put in like a two-hour cap on fatigue or something. in the future, i might institute some better in-game mechanics for fatigue management.

**Comment by modgethanc** [comment]
okay i have no idea what i did or how i lost this function, but it seems that right now, striking while fatigued doesn't actually increase fatigue anymore?

anyway, other thoughts i had about this:
* lower fatigue increase at fatigue strike (right now it's 2x remaining time, but maybe it should be like 1.25x or 1.5x or something, because your strike isn't successful so you're only getting additional fatigue from having attempted)
* cap fatigue at 7200 seconds (2 hours), so the worst damage someone can do to themselves is get barred from striking for two hours

also note for myself: make sure that fatigue strikes aren't incrementing player's total strike count
